import io
import qrcode
from reportlab.pdfgen import canvas
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.files.base import ContentFile
from .models import Box, QR_Code

@receiver(post_save, sender=Box)
def generate_qr_code(sender, instance, created, **kwargs):
    if created:
        box_url = f'http://127.0.0.1:8000/box-king/box/{instance.id}/'

        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(box_url)
        qr.make(fit=True)
        qr_img = qr.make_image(fill='black', back_color='white')

        buffer = io.BytesIO()
        p = canvas.Canvas(buffer)
        p.drawString(100, 750, f"Box Name: {instance.box_name}")
        p.drawString(100, 735, f"Generated by Box King")
        p.drawInlineImage(qr_img, 100, 500, width=200, height=200)
        p.showPage()
        p.save()

        buffer.seek(0)
        qr_code_pdf = buffer.getvalue()
        pdf_content = ContentFile(qr_code_pdf)

        qr_code = QR_Code.objects.create(box=instance)
        qr_code.pdf_file.save(f'{instance.box_name}_{instance.id}.pdf', pdf_content)

        buffer.close()