# Generated by Django 5.1.1 on 2024-10-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='box_id',
            new_name='box',
        ),
        migrations.RenameField(
            model_name='qr_code',
            old_name='box_id',
            new_name='box',
        ),
    ]
