# Generated by Django 5.1.1 on 2024-10-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0002_rename_user_id_box_user_rename_box_id_item_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='box_king.box'),
        ),
    ]
