# Generated by Django 5.1.1 on 2024-10-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0003_alter_item_box'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QR_Code',
        ),
    ]
