# Generated by Django 5.1.1 on 2025-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0004_delete_qr_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('item_name', 'box'), name='unique_item_name_per_box'),
        ),
    ]
