# Generated by Django 5.1.1 on 2025-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0005_item_unique_item_name_per_box'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('item_name', ''), _negated=True), name='item_name_cannot_be_empty_string'),
        ),
    ]
