# Generated by Django 5.1.1 on 2025-03-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0006_item_item_name_cannot_be_empty_string'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_must_be_gt_zero'),
        ),
    ]
