# Generated by Django 5.1.1 on 2025-03-05 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_king', '0007_item_quantity_must_be_gt_zero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('box_name', 'user'), name='unique_box_name_per_user'),
        ),
    ]
